In [2]:
#Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)


print("Data type of list_ variable:", type(list_))
print("Data type of array_list variable:", type(array_list))


Data type of list_ variable: <class 'list'>
Data type of array_list variable: <class 'numpy.ndarray'>


In [4]:
#Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list

In [5]:
list_1 = ['1', '2', '3', '4', '5']
array_list1 = np.array(object=list_1)

print("Data types of elements in list_1:")
for element in list_1:
    print(type(element))

print("\nData types of elements in array_list1:")
for element in array_list1:
    print(type(element))


Data types of elements in list_1:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list1:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [6]:
#Q3. Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int)
#Will there be any difference in the data type of the elements present in both the variables, list_ and 
#arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list

In [9]:
list2 = ['1','2', '3', '4', '5']
array_list2 = np.array(object=list2, dtype=int)

print("Data types of elements in list2:")
for element in list2:
    print(type(element))

print("\nData types of elements in array_list2:")
for element in array_list2:
    print(type(element))


Data types of elements in list2:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list2:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [10]:
#Q4. Write a code to find the following characteristics of variable, num_array:
#(i) shape
#(ii) size

In [11]:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Shape of num_array
shape_of_array = num_array.shape
print("Shape of num_array:", shape_of_array)

# (ii) Size of num_array
size_of_array = num_array.size
print("Size of num_array:", size_of_array)

Shape of num_array: (2, 3)
Size of num_array: 6


In [12]:
#Q5.5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function

In [14]:
zero_array = np.zeros((3, 3))

print("3x3 NumPy array containing zeros:")
print(zero_array)

3x3 NumPy array containing zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
#Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [16]:
identity_matrix = np.eye(5)

print("5x5 Identity Matrix:")
print(identity_matrix)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
